# Generated by Django 4.1.1 on 2022-12-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0002_alter_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
