# Generated by Django 4.1.1 on 2022-12-30 10:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0003_alter_category_slug_alter_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="img/")),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
